version: '1.0'
name: publishGiteePage
displayName: publishGiteePage
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - main
stages:
  - name: stage-e654e8c5
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 安装pnpm'
          - pnpm -v || npm i pnpm -g
          - ''
          - '# 执行编译命令'
          - pnpm install && pnpm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./build
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-94054d17
    displayName: 上传
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: build
        notify: []
        strategy:
          retry: '0'
  - name: stage-d455e3d2
    displayName: 发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: build
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
