name: syncToGitee
on:
  push:
    branches:
      - pages
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/pidanmeng'
          dst: 'gitee/pidanmoe'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          mappings: "wechat_live_qrcode=>wechat_live_group"
          static_list: "wechat_live_qrcode"
          force_update: true
          debug: true
          
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: pidanmoe
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: pidanmoe/wechat_live_group
          branch: pages
